// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxkmpycnlzwrtgucfeaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4a21weWNubHp3cnRndWNmZWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3NTg0NTcsImV4cCI6MjA3ODMzNDQ1N30.FiwtD4bw964F4Zzk4UYoeoqKjWZMzD_J-vW752YGGww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});